id: "slack-integration"
version: "1.0.0"
name: "Slack Integration with Thread Support"
description: "Slack integration for Dify with proper thread support and context preservation"
author: "Your Name"
